Fixed bug that caused guild version to be ignored.
BibleBot/BibleBot pull request #154
Opened 2020-02-02 18:00 UTC by Jsewill

These changes fix the bug that was causing the guild version to be ignored when retrieving verses. I hope you're consider this pull request, or implementing some variation of these changes.

2020-02-02 18:02 UTC, vypr commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/handlers/verses.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/vypr/BibleBot/pullRequest?prid=4930192&bid=16307754)

2020-02-02 18:02 UTC, RdrSeraphim requested changes
ignore this comment

2020-02-02 18:04 UTC, RdrSeraphim approved these changes

2020-02-02 18:06 UTC, RdrSeraphim requested changes
I don't see the point in the changes on src/handlers/verses.py. The changes you made in src/handlers/logic/settings/versions.py should already work fine with the existing code.

2020-02-02 18:57 UTC, Jsewill commented
The point is that without them, the guild version (the only way to set a server-wide default version, and to change the default version from the hardcoded RSV) was entirely ignored. It was broken, these changes fix it.

  VerseHandler->process_raw_message reference version setting before changes:

- inline version
- user version
- RSV

After changes:
- inline version
- user version
- guild version
- RSV

  Also, I'd submit that hardcording the RSV value into these lower level version getting functions instead of in some sort of configuration, or a helper function (like was done in the get_version function in `src/handlers/logic/commands/utils.py`), or at least with a control structure when these functions are used.

2020-02-02 20:21 UTC, Jsewill commented
If you don't like the restructuring in verses.py, don't keep it. I only care that the guild version setting actually works.

2020-02-03 08:22 UTC, vypr commented
You're misunderstanding, VerseHandler already does what you intend for it to do. By removing the hardcoded "RSV" value in versions.py, you've fixed the issue and no more is needed.

2020-02-05 05:01 UTC, Jsewill commented
I understand, I just don't have a lot of time to follow up on these things, and I don't need the credit for these changes. I just wanted the bug fixed. Now, I thought I'd help with some refactoring while I was in there, to make it a little clearer, but I didn't care whether those particular changes were kept or not.

2020-02-05 10:18 UTC, merged